name: Build check

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: setup rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0
        override: true
    - name: build project
      run: cargo build --release --verbose